# Generated by Django 4.1.7 on 2023-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0004_alter_hospital_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('head', models.IntegerField(max_length=100)),
            ],
        ),
    ]
