# Generated by Django 4.1.7 on 2023-03-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0005_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='count',
        ),
    ]
