# Generated by Django 4.1.7 on 2023-03-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0006_remove_departments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
