# Generated by Django 4.1.7 on 2023-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAccounts', '0007_departments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='head',
            field=models.CharField(max_length=100),
        ),
    ]
